version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: qwazzq/kittygram_backend
    env_file: .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    image: qwazzq/kittygram_frontend
    env_file: .env

  gateway:
    image: qwazzq/kittygram_gateway
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend